project:
  type: website
  output-dir: docs

website:
  title: "Christy LAI"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/wlai0012
format:
  html:
    theme: minty
    css: styles.css
    code-block-border-left: "#6ac490"
    code-block-bg: "#ebf5ef"





